specVersion: 0.2.0
name: zoombies-subquery
version: 1.0.0
description: Zoom Token mint, burn and approvals, Zoombies NFT events on Moonriver
repository: https://github.com/ryanprice/zoombies-subquery
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x91bc6e169807aaa54802737e1c504b2577d4fafedd5a02c10293b1cd60e39527' # Genesis hash of Moonriver
  endpoint: wss://moonbase-alpha-api.bwarelabs.com/ws/d6e703e6-a9d9-41bd-ab0a-5b96fae88395
  dictionary: 'https://api.subquery.network/sq/subquery/moonbase-alpha-dictionary'
  chaintypes:
    file: "./types.yaml"

dataSources:
  - kind: substrate/Moonbeam
    startBlock: 799150
    processor:
      file: './node_modules/@subql/contract-processors/dist/moonbeam.js'
      options:
        # Must be a key of assets
        abi: "erc20"
        address: "0x8e21404bAd3A1d2327cc6D2B2118f47911a1f316"
    assets:
      erc20:
        file: "./erc20.abi.json"
    mapping:
      file: './dist/index.js'
      handlers:
        - handler: handleMoonriverEvent
          kind: substrate/MoonbeamEvent
          filter:
            ## Topics that follow Ethereum JSON-RPC log filters
            ## https://docs.ethers.io/v5/concepts/events/
            ## With a couple of added benefits:
            ##  - Values don't need to be 0 padded
            ##  - Event fragments can be provided and automatically converted to their id
            topics:
              ## Example valid values:
              # - '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'
              # - Transfer(address,address,u256)
              # - Transfer(address from,address to,uint256 value)

              ## Example of OR filter, will capture Transfer or Approval events
              # - - 'Transfer(address indexed from,address indexed to,uint256 value)'
              #   - 'Approval(address indexed owner, address indexed spender, uint256 value)'

              - Transfer(address indexed from,address indexed to,uint256 value)
              ## topics[1] to topics[3] are the indexed values
              - null
              - null
              - null
  - kind: substrate/Moonbeam
    startBlock: 799150
    processor:
      file: './node_modules/@subql/contract-processors/dist/moonbeam.js'
      options:
        # Must be a key of assets
        abi: erc721
        address: "0x3E7997B8D30AA6216102fb2e9206246e478d57d3"
    assets:
      erc721:
        file: './Zoombies.json'
    mapping:
      file: './dist/index.js'
      handlers:
        # LogCardMinted(address indexed buyer, uint tokenId, uint32 indexed cardTypeId, uint editionNumber)
        - handler: handleLogCardMintedEvent
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - LogCardMinted(address indexed buyer, uint tokenId, uint32 indexed cardTypeId, uint editionNumber)
        # LogPackOpened(address indexed buyer, uint8 rarity)
        - handler: handleLogPackOpenedEvent
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - LogPackOpened(address indexed buyer, uint8 rarity)
        # LogSponsorReward(address sponsor, address affiliate, uint zoomReward)
        - handler: handleLogSponsorRewardEvent
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - LogSponsorReward(address sponsor, address affiliate, uint zoomReward)
        # LogDailyReward(address player, uint newBoosterBalance)
        - handler: handleLogDailyRewardEvent
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - LogDailyReward(address player, uint newBoosterBalance)
        # LogRewardBoosters(address winner, uint boostersAwarded)
        - handler: handleLogRewardBoostersEvent
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - LogRewardBoosters(address winner, uint boostersAwarded)
        # LogSacrificeNFT(address owner, uint256 tokenId, uint16 cardTypeId, uint256 zoomGained)
        - handler: handleLogSacrificeNFTEvent
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - LogSacrificeNFT(address owner, uint256 tokenId, uint16 cardTypeId, uint256 zoomGained)
        # Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
        - handler: handleNFTTransferEvent
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
